monitoredFiles: []
darkMode: true
gameFolder: M:\SteamLibrary\steamapps\common\Starfield
autoScanGameFolder: true
modManagerRepoFolder: M:\Games\ModStaging\Starfield_Steam
autoScanModRepoFolder: false
modManagerExecutable: S:\Games\Vortex\Vortex.exe
modManagerArguments: --user-data S:\Games\VortexSteamData
autoCheckForUpdates: true
lootExePath: M:\Games\Starfield\Tools\LOOT\LOOT.exe
nexusExportFile: nexus_modlist.json
mO2ExportFile: 
webServicePort: 23306
pluginWarning: true
showDiff: true
